plugins:
  - jekyll-archives

jekyll-archives:
  enabled:
    - categories
  layouts:
    category: category_archive
  permalinks:
    category: '/:name/'

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
